- hosts: all
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    pkg: docker
  tasks:
  - name: Install the indicated software
    yum:
      name: '{{pkg}}'
      state: latest
